---
- name: 'Create Kapacitor DSL directories'
  file:
    path:  "{{ item }}"
    state: 'directory'
    recurse: 'yes'
  with_items:
    - "{{ kapacitor_tick_script_dest_dir }}"
    - "{{ kapacitor_tick_template_dest_dir }}"
    - "{{ kapacitor_tick_var_dest_dir }}"
  tags: 'kapacitor-tick'

- name: 'Copy Kapacitor TICK script files'
  copy:
    src:  "{{ item }}"
    dest: "{{ kapacitor_tick_script_dest_dir }}"
  with_fileglob:
    - "{{ kapacitor_tick_script_dir }}/*.tick"
  tags: 'kapacitor-tick'

- name: 'Copy Kapacitor TICK template files'
  copy:
    src:  "{{ item }}"
    dest: "{{ kapacitor_tick_template_dest_dir }}"
  with_fileglob:
    - "{{ kapacitor_tick_template_dir }}/*.tick"
  tags: 'kapacitor-tick'

- name: 'Copy Kapacitor TICK var files'
  copy:
    src:  "{{ item }}"
    dest: "{{ kapacitor_tick_var_dest_dir }}"
  with_fileglob:
    - "{{ kapacitor_tick_var_dir }}/*.json"
  tags: 'kapacitor-tick'

- name: 'Define Kapacitor templates'
  shell: |
      kapacitor define-template {{ item.id }} \
          -type {{ item.type }} \
          -tick {{ item.tick }} \
  with_items: "{{ kapacitor_templates }}"
  tags: 'kapacitor-tick'

- name: 'Define Kapacitor tasks'
  shell: |
      kapacitor define {{ item.id }} \
          {%if item.type is defined %}-type {{ item.type }} \ {% endif %}
          {%if item.vars is defined %}-vars {{ item.vars }} \ {% endif %}
          {%if item.template is defined %}-template {{ item.template }} \ {% endif %}
          {%if item.template is not defined %}-tick {{ item.tick }} \ {% endif %}
          -dbrp {{ item.dbrp }}
  when: item.enabled == true
  with_items: "{{ kapacitor_tasks }}"
  tags: 'kapacitor-tick'

- name: 'Enable / disable Kapacitor tasks'
  shell: "kapacitor {% if item.enabled %}enable{% else %}disable{% endif %} {{ item.id }}"
  when:
    - kapacitor_tasks | length > 0
  with_items: "{{ kapacitor_tasks }}"
  tags:
    - 'kapacitor-tick'
    - 'kapacitor-task'
